const APPTEXT = {
  es: {
    loginPage: {
      switchDarkMode: "Modo Oscuro",
      selectLanguage: "Seleccionar Idioma",
      createAccountTitle: "Crear una Cuenta",
      haveAccount: "¿Aun no tienes una cuenta?",
      signIn: "Registar",
      emailLabel: "Correo Electrónico",
      emailPlaceholder: "Correo Electrónico",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "Contraseña",
      loginButton: "Iniciar Sesión",
      loginWithGoogleButton: "Iniciar Sesión con Google",
    },
    perfilPage: {
      title: "Perfil",
      titleModalConfirm: "Guardado exitosamente",
      messageModalConfirm: "El registro fue eliminado exitosamente",
      buttonSave: "Guardar",
      principal: "Principal",
      suscribeFor: "Suscribirme por",
      aMonth: "al mes",
      chat: "Chat",
      hello: "Hola",
      howAreYou: "Como estas?",
      colors: "Colores",
      principalColor: "Color principal",
      colorTag: "Color tag",
      colorChat: "Color de chats",
      images: "Imagenes",
      imageProfile: "Imagen del perfil",
      profileImage: "Imagen de portada",
    },
    authlayout: {
      dashboard: "Panel",
      earnings: "Ganancias",
      suscriptions: "Suscripciones",
      suscriptionsList: "Listado",
      suscriptionsPlans: "Mis planes",
      notifications: "Notificaciones",
      notificationsList: "Listado",
      surveys: "Encuestas",
      content: "Contenido",
      reports: "Reportes",
      configuration: "Configuracion",
      goToProfile: "Perfil Priv",
      logOut: "Cerrar Sesion",
      modalAlertMessage: "Estas seguro de esto?",
      cancelButton: "Si, cerrar",
    },
    dashboard: {
      title: "Panel",
      buttonManage: "Gestionar",
      welcomeMessage: "¡Bienvenido!",
      totalRevenue: "Ingresos Totales",
      orders: "Órdenes",
      activeSessions: "Sesiones Activas",
      totalSessions: "Total de Sesiones",
      totalRevenueValue: "$10,540",
      ordersValue: "1,056",
      activeSessionsValue: "48",
      totalSessionsValue: "5,420",
      totalRevenuePercentage: "22.45%",
      ordersPercentage: "15.34%",
      activeSessionsPercentage: "18.25%",
      totalSessionsPercentage: "10.24%",
      revenueArrowDirection: "up", // Puedes usar 'up' o 'down' según corresponda
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "Ganancias",
      exportButton: "Exportar",
      exportSuccessTitle: "Correo enviado!",
      exportSuccessMessage: "El correo fue enviado exitosamente.",
      searchPlaceholder: "Buscar...",
      requestPaymentButton: "Solicitar pago",
      printButton: "Imprimir",
      titleModal: "Detalle de ganancia",
      titleAlertModal: "Estas seguro de eliminar?",
      messageAlertModal: "Quieres eliminar este registro?",
      confirmButtonText: "Si, eliminar",
      titleModalConfirm: "Eliminado exitosamente",
      messageModalConfirm: "El registro fue eliminado exitosamente",
      columns: {
        name: "Nombre",
        date: "Fecha",
        status: "Estatus",
        content: "Contenido",
        quantity: "Cantidad",
        acctions: "Acciones",
      },
    },
    subscriptions: {
      columns: {
        image: "Imagen",
        name: "Nombre",
        date: "Fecha",
        quantity: "Cantidad",
        actions: "Acciones",
      },
      modal: {
        title: "Regalar suscripcion",
        labels: {
          email: "Email",
        },
        buttons: {
          giftSubscription: "Regalar Sub",
        },
        messages: {
          emailRequired: "Por favor, ingresa tu correo",
          emailInvalid: "Por favor, ingresa un correo válido",
          emailSentTitle: "Correo enviado!",
          emailSentMessage: "El correo fue enviado exitosamente.",
        },
      },
      header: {
        exportButton: "Exportar",
        title: "Suscripciones",
        giftSubscription: true,
        titleGiftSubscription: "Regalar suscripcion",
      },
      searchPlaceholder: "Buscar...",
      titleAlertModal: "Estas seguro de eliminar?",
      messageAlertModal: "Quieres eliminar este registro?",
      confirmButtonText: "Si, eliminar",
      titleModalConfirm: "Eliminado exitosamente",
      messageModalConfirm: "El registro fue eliminado exitosamente",
    },
    content: {
      modal: {
        title: "Regalar suscripción",
        labels: {
          files: "Archivos",
          name: "Nombre",
          description: "Descripción",
        },
        buttons: {
          createContent: "Crear contenido",
        },
        messages: {
          nameRequired: "Por favor, ingresa el nombre",
          descriptionRequired: "Por favor, ingresa la descripción",
          emailSentTitle: "Funcion no implementada",
          emailSentMessage: "Se agregara posteriormente",
        },
      },
      header: {
        uploadButton: "Subir",
        title: "Contenido",
      },
      card: {
        createContent: "Crear contenido",
      },
    },
    contentDetail: {
      buttonDetails: "Ver",
      buttonDelete: "Eliminar",
    },
    contentDetailPage: {
      buttonCreate: "Crear",
      buttonEdit: "Editar",
      buttonDetails: "Detalle",
      buttonSave: "Guardar",
      alert: {
        title: "Estás seguro de crear?",
        content: "Lo que no hayas guardado se eliminará.",
        confirmButtonText: "Sí, ir a crear",
        titleSecond: "Creado exitosamente",
        contentSecond: "El registro fue creado exitosamente.",
        titleThird: "Editado exitosamente",
        contentThird: "El registro fue editado exitosamente.",
      },
      contentoNoSupport: "Tu navegador no soporta el tag de video.",
      messageError: {
        message: "Por favor, el nombre",
        messageDescription: "Por favor, la descripcion del video",
      },
      inputs: {
        name: "Nombre",
        description: "",
      },
    },
    notificationsPage: {
      title: "Notificaciones",
      messageNotList: "Listado vacio...",
    },
    surveysPage: {
      title: "Encuestas",
      buttonPrincipal: "Agregar encuestas",
      mySurveys: "Mis encuestas",
      publicSurveys: "Encuestas publicas",
      active: "Activo",
      desactive: "Desactiva",
      responses: "Respuestas",
      addSurveys: "Agregar encuestas",
      surveysForm: {
        isActive: "Activa",
        startDate: "Fecha de Inicio",
        endDate: "Fecha de Fin",
        title: "Pregunta",
        responses: "Respuestas",
        addResponse: "Agregar Respuesta",
        submitButton: "Agregar Encuesta",
        cancelButton: "Cancelar",
      },
    },
    reportsPage: {
      title: "Reportes",
      tabs: {
        bar: "Barras",
        pie: "Pastel",
        line: "Lineas",
        radar: "Radares",
        bubble: "Burbujas",
      },
    },
    configurationPage: {
      title: "Configuration",
      creditCard: "Tarjeta",
      content: {
        header: {
          saveButton: "Guardar",
          pageTitle: "Configuración",
        },
        cardTabs: {
          title: "Configuración",
        },
        navigationButtons: {
          backButton: "Atrás",
          saveButton: "Guardar",
        },
        confirmationDialog: {
          title: "¿Estás seguro de volver?",
          text: "Se perderán los cambios no guardados",
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Sí, volver",
        },
      },
      tabs: {
        perfil: {
          title: "Perfil",
          titlePage: "Detalles del perfil",
          subTitlePage: "Ingresa tu información de perfil",
          profileImage: "Imagen de perfil",
          inputs: {
            name: "Nombre",
            lastName: "Apellido",
            email: "Correo electrónico",
            phone: "Número de teléfono",
          },
          regionalSettings: "Configuraciones regionales",
          timeZone: "Configura tu idioma y zona horaria",
          language: "Idioma",
          titleTimeZone: "Zona horaria",
        },

        notifications: {
          title: "Notificaciones",
          personalizedOffers: {
            title: "Ofertas Personalizadas",
            description: "Recibe ofertas especiales para ti",
          },
          onlineWebinars: {
            title: "Webinars en Línea",
            description: "Recibe notificaciones sobre próximos webinars",
          },
          newFeatures: {
            title: "Nuevas Funciones",
            description:
              "Actualizaciones sobre nuevas funciones y lanzamientos de productos",
          },
          securityBilling: {
            title: "Seguridad y Facturación",
            description:
              "Notificaciones sobre seguridad de la cuenta y facturación",
          },
          marketing: {
            title: "Marketing",
            description:
              "Recibe boletines de marketing sobre nuestros nuevos productos",
          },
        },
        accountSecurityPage: {
          title: "Cuenta y Seguridad",
          unsubscribe: {
            title: "Darse de Baja",
            description: "Eliminar cuenta",
          },
          backup: {
            title: "Copia de Seguridad",
            description: "Copia de seguridad",
            deleteButton: "Eliminar",
          },
          paymentMethod: {
            title: "Método de Pago",
            addButton: "Agregar",
          },
        },
      },
    },
  },
  en: {
    loginPage: {
      switchDarkMode: "Switch Dark Mode",
      selectLanguage: "Select Language",
      createAccountTitle: "Create an Account",
      haveAccount: "Do not you have an account yet?",
      signIn: "To register",
      emailLabel: "Email",
      emailPlaceholder: "Email",
      passwordLabel: "Password",
      passwordPlaceholder: "Password",
      loginButton: "Login",
      googleLogin: "Google Login",
    },
    perfilPage: {
      title: "Profile",
      titleModalConfirm: "Saved successfully",
      messageModalConfirm: "The record was deleted successfully",
      buttonSave: "Save",
      principal: "Principal",
      suscribeFor: "Subscribe for",
      aMonth: "per month",
      chat: "Chat",
      hello: "Hello",
      howAreYou: "How are you?",
      colors: "Colors",
      principalColor: "Main color",
      colorTag: "Tag color",
      colorChat: "Chat color",
      images: "Images",
      imageProfile: "Profile image",
      profileImage: "Cover image",
    },
    authlayout: {
      dashboard: "Dashboard",
      earnings: "Earnings",
      suscriptions: "Suscriptions",
      suscriptionsList: "List",
      suscriptionsPlans: "My plans",
      notifications: "Notifications",
      notificationsList: "List",
      surveys: "Surveys",
      content: "Content",
      reports: "Reports",
      configuration: "Configuration",
      goToProfile: "Profile Priv",
      logOut: "Log Out",
      modalAlertMessage: "Are you sure about this action?",
      cancelButton: "Yes, close",
    },
    dashboard: {
      title: "Dashboard",
      buttonManage: "Manage",
      welcomeMessage: "Welcome!",
      totalRevenue: "Total Revenue",
      orders: "Orders",
      activeSessions: "Active Sessions",
      totalSessions: "Total Sessions",
      totalRevenueValue: "$10,540",
      ordersValue: "1,056",
      activeSessionsValue: "48",
      totalSessionsValue: "5,420",
      totalRevenuePercentage: "22.45%",
      ordersPercentage: "15.34%",
      activeSessionsPercentage: "18.25%",
      totalSessionsPercentage: "10.24%",
      revenueArrowDirection: "up",
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "Earnings",
      exportButton: "Export",
      exportSuccessTitle: "Email sent!",
      exportSuccessMessage: "The email was sent successfully.",
      searchPlaceholder: "Search...",
      requestPaymentButton: "Request payment",
      printButton: "Print",
      titleModal: "Detail of earning",
      titleAlertModal: "Are you sure to delete?",
      messageAlertModal: "Do you want to delete this record?",
      confirmButtonText: "Yes, delete",
      titleModalConfirm: "Deleted successfully",
      messageModalConfirm: "The register has deleted successfully",
      columns: {
        name: "Name",
        date: "Date",
        status: "Status",
        content: "Content",
        quantity: "Quantity",
        acctions: "Acctions",
      },
    },
    subscriptions: {
      columns: {
        image: "Image",
        name: "Name",
        date: "Date",
        quantity: "Quantity",
        actions: "Actions",
      },
      modal: {
        title: "Gift subscription",
        labels: {
          email: "Email",
        },
        buttons: {
          giftSubscription: "Gift Sub",
        },
        messages: {
          emailRequired: "Please enter your email",
          emailInvalid: "Please enter a valid email",
          emailSentTitle: "Email sent!",
          emailSentMessage: "The email was sent successfully.",
        },
      },
      header: {
        exportButton: "Export",
        title: "Subscriptions",
        giftSubscription: true,
        titleGiftSubscription: "Gift subscription",
      },
      searchPlaceholder: "Search...",
      titleAlertModal: "Are you sure to delete?",
      messageAlertModal: "Do you want to delete this record?",
      confirmButtonText: "Yes, delete",
      titleModalConfirm: "Deleted successfully",
      messageModalConfirm: "The register has deleted successfully",
    },
    content: {
      modal: {
        title: "Gift subscription",
        labels: {
          files: "Files",
          name: "Name",
          description: "Description",
        },
        buttons: {
          createContent: "Create content",
        },
        messages: {
          nameRequired: "Please enter the name",
          descriptionRequired: "Please enter the description",
          emailSentTitle: "Function no implemented",
          emailSentMessage: "Will be implemented in future",
        },
      },
      header: {
        uploadButton: "Upload",
        title: "Content",
      },
      card: {
        createContent: "Create content",
      },
    },
    contentDetail: {
      buttonDetails: "View",
      buttonDelete: "Delete",
    },
    contentDetailPage: {
      buttonCreate: "Create",
      buttonEdit: "Edit",
      buttonDetails: "Details",
      buttonSave: "Save",
      alert: {
        title: "Are you sure to create?",
        content: "What you haven't saved will be deleted.",
        confirmButtonText: "Yes, go to create",
        titleSecond: "Created successfully",
        contentSecond: "The record was created successfully.",
        titleThird: "Edited successfully",
        contentThird: "The record was edited successfully.",
      },
      contentoNoSupport: "Your browser does not support the video tag.",
      messageError: {
        message: "Please enter the name",
        messageDescription: "Please enter the video description",
      },
      inputs: {
        name: "Name",
        description: "Description",
      },
    },
    notificationsPage: {
      title: "Notifications",
      messageNotList: "List empty...",
    },
    surveysPage: {
      title: "Surveys",
      buttonPrincipal: "Add Survey",
      mySurveys: "My Surveys",
      publicSurveys: "Public surveys",
      active: "Active",
      desactive: "Disabled",
      responses: "Responses",
      addSurveys: "Add Survey",
    },
    reportsPage: {
      title: "Reports",
      tabs: {
        bar: "Bars",
        pie: "Pie",
        line: "Line",
        radar: "Radar",
        bubble: "Bubble",
      },
    },
    configurationPage: {
      title: "Configuration",
      creditCard: "Credit Card",
      content: {
        header: {
          saveButton: "Save",
          pageTitle: "Configuration",
        },
        cardTabs: {
          title: "Configuration",
        },
        navigationButtons: {
          backButton: "Back",
          saveButton: "Save",
        },
        confirmationDialog: {
          title: "Are you sure you want to go back?",
          text: "Unsaved changes will be lost",
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Yes, go back",
        },
      },
      tabs: {
        perfil: {
          title: "Perfil",
          titlePage: "Details profile",
          subTitlePage: "Enter your profile information",
          profileImage: "Profile Image",
          inputs: {
            name: "First Name",
            lastName: "Last Name",
            email: "Email",
            phone: "Phone Number",
          },
          regionalSettings: "Regional Settings",
          timeZone: "Set your language and timezone",
          language: "Language",
          titleTimeZone: "Timezone",
        },
        notifications: {
          title: "Notifications",
          personalizedOffers: {
            title: "Personalized Offers",
            description: "Receive offers made special for you",
          },
          onlineWebinars: {
            title: "Online Webinars",
            description: "Get notified about upcoming webinars",
          },
          newFeatures: {
            title: "New Features",
            description: "Updates about new features and product releases",
          },
          securityBilling: {
            title: "Security and Billing",
            description: "Account security and notifications about billing",
          },
          marketing: {
            title: "Marketing",
            description: "Receive marketing newsletters about our new products",
          },
        },
        accountSecurityPage: {
          title: "Account and Security",
          unsubscribe: {
            title: "Unsubscribe",
            description: "Delete account",
          },
          backup: {
            title: "Backup",
            description: "Backup",
            deleteButton: "Delete",
          },
          paymentMethod: {
            title: "Payment Method",
            addButton: "Add",
          },
        },
      },
    },
  },
  "pt-br": {
    loginPage: {
      switchDarkMode: "Ativar Modo Escuro",
      selectLanguage: "Selecionar Idioma",
      createAccountTitle: "Criar uma Conta",
      haveAccount: "Ainda não tem uma conta?",
      signIn: "Cadastrar",
      emailLabel: "E-mail",
      emailPlaceholder: "E-mail",
      passwordLabel: "Senha",
      passwordPlaceholder: "Senha",
      loginButton: "Entrar",
      googleLogin: "Login com Google",
    },
    perfilPage: {
      title: "Perfil",
      titleModalConfirm: "Salvo com sucesso",
      messageModalConfirm: "O registro foi excluído com sucesso",
      buttonSave: "Salvar",
      principal: "Principal",
      suscribeFor: "Assinar por",
      aMonth: "por mês",
      chat: "Chat",
      hello: "Olá",
      howAreYou: "Como você está?",
      colors: "Cores",
      principalColor: "Cor principal",
      colorTag: "Cor da tag",
      colorChat: "Cor do chat",
      images: "Imagens",
      imageProfile: "Imagem do perfil",
      profileImage: "Imagem de capa",
    },
    authlayout: {
      dashboard: "Dashboard",
      earnings: "Ganhos",
      suscriptions: "Inscrições",
      suscriptionsList: "Lista",
      suscriptionsPlans: "Meus planos",
      notifications: "Notificações",
      notificationsList: "Lista",
      surveys: "Pesquisas",
      content: "Conteúdo",
      reports: "Relatórios",
      configuration: "Configuração",
      goToProfile: "Perfil Privado",
      logOut: "Sair",
      modalAlertMessage: "Tem certeza desta ação?",
      cancelButton: "Sim, fechar",
    },
    dashboard: {
      title: "Dashboard",
      buttonManage: "Gerenciar",
      welcomeMessage: "Bem-vindo!",
      totalRevenue: "Receita Total",
      orders: "Pedidos",
      activeSessions: "Sessões Ativas",
      totalSessions: "Sessões Totais",
      totalRevenueValue: "$10,540",
      ordersValue: "1,056",
      activeSessionsValue: "48",
      totalSessionsValue: "5,420",
      totalRevenuePercentage: "22.45%",
      ordersPercentage: "15.34%",
      activeSessionsPercentage: "18.25%",
      totalSessionsPercentage: "10.24%",
      revenueArrowDirection: "up",
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "Ganhos",
      exportButton: "Exportar",
      exportSuccessTitle: "E-mail enviado!",
      exportSuccessMessage: "O e-mail foi enviado com sucesso.",
      searchPlaceholder: "Buscar...",
      requestPaymentButton: "Solicitar pagamento",
      printButton: "Imprimir",
      titleModal: "Detalhes dos ganhos",
      titleAlertModal: "Tem certeza de que deseja excluir?",
      messageAlertModal: "Você deseja excluir este registro?",
      confirmButtonText: "Sim, excluir",
      titleModalConfirm: "Excluído com sucesso",
      messageModalConfirm: "O registro foi excluído com sucesso",
      columns: {
        name: "Nome",
        date: "Data",
        status: "Status",
        content: "Conteúdo",
        quantity: "Quantidade",
        acctions: "Ações",
      },
    },
    subscriptions: {
      columns: {
        image: "Imagem",
        name: "Nome",
        date: "Data",
        quantity: "Quantidade",
        actions: "Ações",
      },
      modal: {
        title: "Assinatura de presente",
        labels: {
          email: "E-mail",
        },
        buttons: {
          giftSubscription: "Presentear",
        },
        messages: {
          emailRequired: "Por favor, insira seu e-mail",
          emailInvalid: "Por favor, insira um e-mail válido",
          emailSentTitle: "E-mail enviado!",
          emailSentMessage: "O e-mail foi enviado com sucesso.",
        },
      },
      header: {
        exportButton: "Exportar",
        title: "Inscrições",
        giftSubscription: true,
        titleGiftSubscription: "Assinatura de presente",
      },
      searchPlaceholder: "Buscar...",
      titleAlertModal: "Tem certeza de que deseja excluir?",
      messageAlertModal: "Você deseja excluir este registro?",
      confirmButtonText: "Sim, excluir",
      titleModalConfirm: "Excluído com sucesso",
      messageModalConfirm: "O registro foi excluído com sucesso",
    },
    content: {
      modal: {
        title: "Assinatura de presente",
        labels: {
          files: "Arquivos",
          name: "Nome",
          description: "Descrição",
        },
        buttons: {
          createContent: "Criar conteúdo",
        },
        messages: {
          nameRequired: "Por favor, insira o nome",
          descriptionRequired: "Por favor, insira a descrição",
          emailSentTitle: "Função não implementada",
          emailSentMessage: "Será implementada no futuro",
        },
      },
      header: {
        uploadButton: "Enviar",
        title: "Conteúdo",
      },
      card: {
        createContent: "Criar conteúdo",
      },
    },
    contentDetail: {
      buttonDetails: "Visualizar",
      buttonDelete: "Excluir",
    },
    contentDetailPage: {
      buttonCreate: "Criar",
      buttonEdit: "Editar",
      buttonDetails: "Detalhes",
      buttonSave: "Salvar",
      alert: {
        title: "Tem certeza de que deseja criar?",
        content: "O que não foi salvo será excluído.",
        confirmButtonText: "Sim, ir para criar",
        titleSecond: "Criado com sucesso",
        contentSecond: "O registro foi criado com sucesso.",
        titleThird: "Editado com sucesso",
        contentThird: "O registro foi editado com sucesso.",
      },
      contentoNoSupport: "Seu navegador não suporta a tag de vídeo.",
      messageError: {
        message: "Por favor, insira o nome",
        messageDescription: "Por favor, insira a descrição do vídeo",
      },
      inputs: {
        name: "Nome",
        description: "Descrição",
      },
    },
    notificationsPage: {
      title: "Notificações",
      messageNotList: "Lista vazia...",
    },
    surveysPage: {
      title: "Pesquisas",
      buttonPrincipal: "Adicionar Pesquisa",
      mySurveys: "Minhas Pesquisas",
      publicSurveys: "Pesquisas públicas",
      active: "Ativas",
      desactive: "Desativadas",
      responses: "Respostas",
      addSurveys: "Adicionar Pesquisa",
    },
    reportsPage: {
      title: "Relatórios",
      tabs: {
        bar: "Barras",
        pie: "Pizza",
        line: "Linha",
        radar: "Radar",
        bubble: "Bolha",
      },
    },
    configurationPage: {
      title: "Configuração",
      creditCard: "Cartão de Crédito",
      content: {
        header: {
          saveButton: "Salvar",
          pageTitle: "Configuração",
        },
        cardTabs: {
          title: "Configuração",
        },
        navigationButtons: {
          backButton: "Voltar",
          saveButton: "Salvar",
        },
        confirmationDialog: {
          title: "Tem certeza de que deseja voltar?",
          text: "As alterações não salvas serão perdidas",
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Sim, voltar",
        },
      },
      tabs: {
        perfil: {
          title: "Perfil",
          titlePage: "Detalhes do perfil",
          subTitlePage: "Insira suas informações de perfil",
          profileImage: "Imagem do Perfil",
          inputs: {
            name: "Primeiro Nome",
            lastName: "Sobrenome",
            email: "E-mail",
            phone: "Número de Telefone",
          },
          regionalSettings: "Configurações Regionais",
          timeZone: "Configurar seu idioma e fuso horário",
          language: "Idioma",
          titleTimeZone: "Fuso Horário",
        },
        notifications: {
          title: "Notificações",
          personalizedOffers: {
            title: "Ofertas Personalizadas",
            description: "Receba ofertas especiais feitas para você",
          },
          onlineWebinars: {
            title: "Webinars Online",
            description: "Receba notificações sobre próximos webinars",
          },
          newFeatures: {
            title: "Novas Funcionalidades",
            description:
              "Atualizações sobre novas funcionalidades e lançamentos de produtos",
          },
          securityBilling: {
            title: "Segurança e Faturamento",
            description: "Segurança da conta e notificações sobre faturamento",
          },
          marketing: {
            title: "Marketing",
            description:
              "Receba boletins de marketing sobre nossos novos produtos",
          },
        },
        accountSecurityPage: {
          title: "Conta e Segurança",
          unsubscribe: {
            title: "Cancelar Inscrição",
            description: "Excluir conta",
          },
          backup: {
            title: "Backup",
            description: "Backup",
            deleteButton: "Excluir",
          },
          paymentMethod: {
            title: "Método de Pagamento",
            addButton: "Adicionar",
          },
        },
      },
    },
  },
  "zh-cn": {
    loginPage: {
      switchDarkMode: "切换深色模式",
      selectLanguage: "选择语言",
      createAccountTitle: "创建账户",
      haveAccount: "还没有帐户吗？",
      signIn: "注册",
      emailLabel: "邮箱",
      emailPlaceholder: "邮箱",
      passwordLabel: "密码",
      passwordPlaceholder: "密码",
      loginButton: "登录",
      googleLogin: "Google登录",
    },
    perfilPage: {
      title: "个人资料",
      titleModalConfirm: "保存成功",
      messageModalConfirm: "记录已成功删除",
      buttonSave: "保存",
      principal: "主要",
      suscribeFor: "订阅",
      aMonth: "每月",
      chat: "聊天",
      hello: "你好",
      howAreYou: "你好吗？",
      colors: "颜色",
      principalColor: "主色",
      colorTag: "标签颜色",
      colorChat: "聊天颜色",
      images: "图片",
      imageProfile: "个人资料图片",
      profileImage: "封面图片",
    },
    authlayout: {
      dashboard: "仪表板",
      earnings: "收益",
      suscriptions: "订阅",
      suscriptionsList: "列表",
      suscriptionsPlans: "我的计划",
      notifications: "通知",
      notificationsList: "列表",
      surveys: "调查",
      content: "内容",
      reports: "报告",
      configuration: "配置",
      goToProfile: "个人资料",
      logOut: "退出",
      modalAlertMessage: "您确定要执行此操作吗？",
      cancelButton: "是的，关闭",
    },
    dashboard: {
      title: "仪表板",
      buttonManage: "管理",
      welcomeMessage: "欢迎!",
      totalRevenue: "总收入",
      orders: "订单",
      activeSessions: "活跃会话",
      totalSessions: "总会话数",
      totalRevenueValue: "$10,540",
      ordersValue: "1,056",
      activeSessionsValue: "48",
      totalSessionsValue: "5,420",
      totalRevenuePercentage: "22.45%",
      ordersPercentage: "15.34%",
      activeSessionsPercentage: "18.25%",
      totalSessionsPercentage: "10.24%",
      revenueArrowDirection: "up",
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "收益",
      exportButton: "导出",
      exportSuccessTitle: "邮件已发送！",
      exportSuccessMessage: "邮件已成功发送。",
      searchPlaceholder: "搜索...",
      requestPaymentButton: "请求付款",
      printButton: "打印",
      titleModal: "收入明细",
      titleAlertModal: "确定要删除吗？",
      messageAlertModal: "您是否要删除此记录？",
      confirmButtonText: "是的，删除",
      titleModalConfirm: "删除成功",
      messageModalConfirm: "记录已成功删除",
      columns: {
        name: "名称",
        date: "日期",
        status: "状态",
        content: "内容",
        quantity: "数量",
        acctions: "操作",
      },
    },
    subscriptions: {
      columns: {
        image: "图像",
        name: "名称",
        date: "日期",
        quantity: "数量",
        actions: "操作",
      },
      modal: {
        title: "礼品订阅",
        labels: {
          email: "电子邮件",
        },
        buttons: {
          giftSubscription: "礼品订阅",
        },
        messages: {
          emailRequired: "请输入您的电子邮件",
          emailInvalid: "请输入有效的电子邮件",
          emailSentTitle: "邮件已发送！",
          emailSentMessage: "邮件已成功发送。",
        },
      },
      header: {
        exportButton: "导出",
        title: "订阅",
        giftSubscription: true,
        titleGiftSubscription: "礼品订阅",
      },
      searchPlaceholder: "搜索...",
      titleAlertModal: "确定要删除吗？",
      messageAlertModal: "您是否要删除此记录？",
      confirmButtonText: "是的，删除",
      titleModalConfirm: "删除成功",
      messageModalConfirm: "记录已成功删除",
    },
    content: {
      modal: {
        title: "礼品订阅",
        labels: {
          files: "文件",
          name: "名称",
          description: "描述",
        },
        buttons: {
          createContent: "创建内容",
        },
        messages: {
          nameRequired: "请输入名称",
          descriptionRequired: "请输入描述",
          emailSentTitle: "功能未实现",
          emailSentMessage: "将在将来实现",
        },
      },
      header: {
        uploadButton: "上传",
        title: "内容",
      },
      card: {
        createContent: "创建内容",
      },
    },
    contentDetail: {
      buttonDetails: "查看",
      buttonDelete: "删除",
    },
    contentDetailPage: {
      buttonCreate: "创建",
      buttonEdit: "编辑",
      buttonDetails: "详情",
      buttonSave: "保存",
      alert: {
        title: "确定要创建吗？",
        content: "未保存的内容将被删除。",
        confirmButtonText: "是的，去创建",
        titleSecond: "创建成功",
        contentSecond: "记录已成功创建。",
        titleThird: "编辑成功",
        contentThird: "记录已成功编辑。",
      },
      contentoNoSupport: "您的浏览器不支持视频标签。",
      messageError: {
        message: "请输入名称",
        messageDescription: "请输入视频描述",
      },
      inputs: {
        name: "名称",
        description: "描述",
      },
    },
    notificationsPage: {
      title: "通知",
      messageNotList: "列表为空...",
    },
    surveysPage: {
      title: "调查",
      buttonPrincipal: "添加调查",
      mySurveys: "我的调查",
      publicSurveys: "公共调查",
      active: "激活",
      desactive: "禁用",
      responses: "响应",
      addSurveys: "添加调查",
    },
    reportsPage: {
      title: "报告",
      tabs: {
        bar: "柱状图",
        pie: "饼图",
        line: "折线图",
        radar: "雷达图",
        bubble: "气泡图",
      },
    },
    configurationPage: {
      title: "配置",
      creditCard: "信用卡",
      content: {
        header: {
          saveButton: "保存",
          pageTitle: "配置",
        },
        cardTabs: {
          title: "配置",
        },
        navigationButtons: {
          backButton: "返回",
          saveButton: "保存",
        },
        confirmationDialog: {
          title: "您确定要返回吗？",
          text: "未保存的更改将丢失",
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "是的，返回",
        },
      },
      tabs: {
        perfil: {
          title: "个人资料",
          titlePage: "详细资料",
          subTitlePage: "输入个人资料",
          profileImage: "个人形象",
          inputs: {
            name: "名字",
            lastName: "姓",
            email: "电子邮件",
            phone: "电话号码",
          },
          regionalSettings: "区域设置",
          timeZone: "设置语言和时区",
          language: "语言",
          titleTimeZone: "时区",
        },
        notifications: {
          title: "通知",
          personalizedOffers: {
            title: "个性化优惠",
            description: "收到专为您制作的优惠",
          },
          onlineWebinars: {
            title: "在线网络研讨会",
            description: "获取有关即将举行的网络研讨会的通知",
          },
          newFeatures: {
            title: "新功能",
            description: "关于新功能和产品发布的更新",
          },
          securityBilling: {
            title: "安全和账单",
            description: "账户安全性和有关计费的通知",
          },
          marketing: {
            title: "营销",
            description: "接收有关我们新产品的营销通讯",
          },
        },
        accountSecurityPage: {
          title: "账户和安全",
          unsubscribe: {
            title: "退订",
            description: "删除账户",
          },
          backup: {
            title: "备份",
            description: "备份",
            deleteButton: "删除",
          },
          paymentMethod: {
            title: "付款方式",
            addButton: "添加",
          },
        },
      },
    },
  },
  fr: {
    loginPage: {
      switchDarkMode: "Activer le mode sombre",
      selectLanguage: "Sélectionner la langue",
      createAccountTitle: "Créer un compte",
      haveAccount: "Vous n'avez pas de compte?",
      signIn: "注册",
      emailLabel: "E-mail",
      emailPlaceholder: "E-mail",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "Mot de passe",
      loginButton: "Se connecter",
      googleLogin: "Connexion Google",
    },
    perfilPage: {
      title: "Profil",
      titleModalConfirm: "Enregistré avec succès",
      messageModalConfirm: "L'enregistrement a été supprimé avec succès",
      buttonSave: "Enregistrer",
      principal: "Principal",
      suscribeFor: "S'abonner pour",
      aMonth: "par mois",
      chat: "Chat",
      hello: "Bonjour",
      howAreYou: "Comment ça va ?",
      colors: "Couleurs",
      principalColor: "Couleur principale",
      colorTag: "Couleur de la balise",
      colorChat: "Couleur du chat",
      images: "Images",
      imageProfile: "Image de profil",
      profileImage: "Image de couverture",
    },
    authlayout: {
      dashboard: "Tableau de bord",
      earnings: "Gains",
      suscriptions: "Abonnements",
      suscriptionsList: "Liste",
      suscriptionsPlans: "Mes plans",
      notifications: "Notifications",
      notificationsList: "Liste",
      surveys: "Sondages",
      content: "Contenu",
      reports: "Rapports",
      configuration: "Configuration",
      goToProfile: "Profil",
      logOut: "Déconnexion",
      modalAlertMessage: "Êtes-vous sûr de cette action ?",
      cancelButton: "Oui, fermer",
    },
    dashboard: {
      title: "Tableau de bord",
      buttonManage: "Gérer",
      welcomeMessage: "Bienvenue!",
      totalRevenue: "Chiffre d'affaires total",
      orders: "Commandes",
      activeSessions: "Sessions actives",
      totalSessions: "Sessions totales",
      totalRevenueValue: "10 540 $",
      ordersValue: "1 056",
      activeSessionsValue: "48",
      totalSessionsValue: "5 420",
      totalRevenuePercentage: "22,45%",
      ordersPercentage: "15,34%",
      activeSessionsPercentage: "18,25%",
      totalSessionsPercentage: "10,24%",
      revenueArrowDirection: "up",
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "Gains",
      exportButton: "Exporter",
      exportSuccessTitle: "E-mail envoyé !",
      exportSuccessMessage: "L'e-mail a été envoyé avec succès.",
      searchPlaceholder: "Rechercher...",
      requestPaymentButton: "Demander un paiement",
      printButton: "Imprimer",
      titleModal: "Détail du gain",
      titleAlertModal: "Êtes-vous sûr de vouloir supprimer ?",
      messageAlertModal: "Voulez-vous supprimer cet enregistrement ?",
      confirmButtonText: "Oui, supprimer",
      titleModalConfirm: "Supprimé avec succès",
      messageModalConfirm: "L'enregistrement a été supprimé avec succès",
      columns: {
        name: "Nom",
        date: "Date",
        status: "Statut",
        content: "Contenu",
        quantity: "Quantité",
        acctions: "Actions",
      },
    },
    subscriptions: {
      columns: {
        image: "Image",
        name: "Nom",
        date: "Date",
        quantity: "Quantité",
        actions: "Actions",
      },
      modal: {
        title: "Abonnement cadeau",
        labels: {
          email: "E-mail",
        },
        buttons: {
          giftSubscription: "Abonnement cadeau",
        },
        messages: {
          emailRequired: "Veuillez saisir votre e-mail",
          emailInvalid: "Veuillez saisir une adresse e-mail valide",
          emailSentTitle: "E-mail envoyé !",
          emailSentMessage: "L'e-mail a été envoyé avec succès.",
        },
      },
      header: {
        exportButton: "Exporter",
        title: "Abonnements",
        giftSubscription: true,
        titleGiftSubscription: "Abonnement cadeau",
      },
      searchPlaceholder: "Rechercher...",
      titleAlertModal: "Êtes-vous sûr de vouloir supprimer ?",
      messageAlertModal: "Voulez-vous supprimer cet enregistrement ?",
      confirmButtonText: "Oui, supprimer",
      titleModalConfirm: "Supprimé avec succès",
      messageModalConfirm: "L'enregistrement a été supprimé avec succès",
    },
    content: {
      modal: {
        title: "Abonnement cadeau",
        labels: {
          files: "Fichiers",
          name: "Nom",
          description: "Description",
        },
        buttons: {
          createContent: "Créer du contenu",
        },
        messages: {
          nameRequired: "Veuillez entrer le nom",
          descriptionRequired: "Veuillez entrer la description",
          emailSentTitle: "Fonction non implémentée",
          emailSentMessage: "Sera implémenté dans le futur",
        },
      },
      header: {
        uploadButton: "Télécharger",
        title: "Contenu",
      },
      card: {
        createContent: "Créer du contenu",
      },
    },
    contentDetail: {
      buttonDetails: "Voir",
      buttonDelete: "Supprimer",
    },
    contentDetailPage: {
      buttonCreate: "Créer",
      buttonEdit: "Éditer",
      buttonDetails: "Détails",
      buttonSave: "Enregistrer",
      alert: {
        title: "Êtes-vous sûr de vouloir créer ?",
        content: "Ce que vous n'avez pas enregistré sera supprimé.",
        confirmButtonText: "Oui, passer à la création",
        titleSecond: "Créé avec succès",
        contentSecond: "L'enregistrement a été créé avec succès.",
        titleThird: "Édité avec succès",
        contentThird: "L'enregistrement a été édité avec succès.",
      },
      contentoNoSupport:
        "Votre navigateur ne prend pas en charge la balise vidéo.",
      messageError: {
        message: "Veuillez entrer le nom",
        messageDescription: "Veuillez entrer la description de la vidéo",
      },
      inputs: {
        name: "Nom",
        description: "Description",
      },
    },
    notificationsPage: {
      title: "Notifications",
      messageNotList: "Liste vide...",
    },
    surveysPage: {
      title: "Sondages",
      buttonPrincipal: "Ajouter un sondage",
      mySurveys: "Mes sondages",
      publicSurveys: "Sondages publics",
      active: "Actif",
      desactive: "Désactivé",
      responses: "Réponses",
      addSurveys: "Ajouter un sondage",
    },
    reportsPage: {
      title: "Rapports",
      tabs: {
        bar: "Barres",
        pie: "Camembert",
        line: "Ligne",
        radar: "Radar",
        bubble: "Bulle",
      },
    },
    configurationPage: {
      title: "Configuration",
      creditCard: "Carte de crédit",
      content: {
        header: {
          saveButton: "Enregistrer",
          pageTitle: "Configuration",
        },
        cardTabs: {
          title: "Configuration",
        },
        navigationButtons: {
          backButton: "Retour",
          saveButton: "Enregistrer",
        },
        confirmationDialog: {
          title: "Êtes-vous sûr de vouloir revenir en arrière ?",
          text: "Les modifications non enregistrées seront perdues",
          confirmButtonColor: "#3085d6",
          cancelButtonColor: "#d33",
          confirmButtonText: "Oui, revenir",
        },
      },
      tabs: {
        perfil: {
          title: "Profil",
          titlePage: "Détails du profil",
          subTitlePage: "Saisissez vos informations de profil",
          profileImage: "Image de profil",
          inputs: {
            name: "Prénom",
            lastName: "Nom de famille",
            email: "E-mail",
            phone: "Numéro de téléphone",
          },
          regionalSettings: "Paramètres régionaux",
          timeZone: "Définissez votre langue et votre fuseau horaire",
          language: "Langue",
          titleTimeZone: "Fuseau horaire",
        },
        notifications: {
          title: "Notifications",
          personalizedOffers: {
            title: "Offres personnalisées",
            description: "Recevez des offres spéciales pour vous",
          },
          onlineWebinars: {
            title: "Webinaires en ligne",
            description: "Recevez des notifications sur les webinaires à venir",
          },
          newFeatures: {
            title: "Nouvelles fonctionnalités",
            description:
              "Mises à jour sur les nouvelles fonctionnalités et les sorties de produits",
          },
          securityBilling: {
            title: "Sécurité et facturation",
            description:
              "Sécurité du compte et notifications concernant la facturation",
          },
          marketing: {
            title: "Marketing",
            description:
              "Recevez des newsletters marketing sur nos nouveaux produits",
          },
        },
        accountSecurityPage: {
          title: "Compte et sécurité",
          unsubscribe: {
            title: "Se désabonner",
            description: "Supprimer le compte",
          },
          backup: {
            title: "Sauvegarde",
            description: "Sauvegarde",
            deleteButton: "Supprimer",
          },
          paymentMethod: {
            title: "Moyen de paiement",
            addButton: "Ajouter",
          },
        },
      },
    },
  },
};

export default APPTEXT;
