const APPTEXT = {
  es: {
    authlayout: {
      dashboard: "Panel",
      earnings: "Ganancias",
      suscriptions: "Suscripciones",
      suscriptionsList: "Listado",
      suscriptionsPlans: "Mis planes",
      notifications: "Notificaciones",
      notificationsList: "Listado",
      surveys: "Encuestas",
      content: "Contenido",
      reports: "Reportes",
      configuration: "Configuracion",
      goToProfile: "Perfil Priv",
      logOut: "Cerrar Sesion",
    },
    dashboard: {
      title: "Panel",
      buttonManage: "Gestionar",
      welcomeMessage: "¡Bienvenido nombre!",
      totalRevenue: "Ingresos Totales",
      orders: "Órdenes",
      activeSessions: "Sesiones Activas",
      totalSessions: "Total de Sesiones",
      totalRevenueValue: "$10,540",
      ordersValue: "1,056",
      activeSessionsValue: "48",
      totalSessionsValue: "5,420",
      totalRevenuePercentage: "22.45%",
      ordersPercentage: "15.34%",
      activeSessionsPercentage: "18.25%",
      totalSessionsPercentage: "10.24%",
      revenueArrowDirection: "up", // Puedes usar 'up' o 'down' según corresponda
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "Ganancias",
      exportButton: "Exportar",
      exportSuccessTitle: "Correo enviado!",
      exportSuccessMessage: "El correo fue enviado exitosamente.",
      searchPlaceholder: "Buscar...",
      requestPaymentButton: "Solicitar pago",
      printButton: "Imprimir",
      titleModal: "Detalle de ganancia",
      titleAlertModal: "Estas seguro de eliminar?",
      messageAlertModal: "Quieres eliminar este registro?",
      confirmButtonText: "Si, eliminar",
      titleModalConfirm: "Eliminado exitosamente",
      messageModalConfirm: "El registro fue eliminado exitosamente",
      columns: {
        name: "Nombre",
        date: "Fecha",
        status: "Estatus",
        content: "Contenido",
        quantity: "Cantidad",
        acctions: "Acciones",
      },
    },
    subscriptions: {
      columns: {
        image: "Imagen",
        name: "Nombre",
        date: "Fecha",
        quantity: "Cantidad",
        actions: "Acciones",
      },
      modal: {
        title: "Regalar suscripcion",
        labels: {
          email: "Email",
        },
        buttons: {
          giftSubscription: "Regalar Sub",
        },
        messages: {
          emailRequired: "Por favor, ingresa tu correo",
          emailInvalid: "Por favor, ingresa un correo válido",
          emailSentTitle: "Correo enviado!",
          emailSentMessage: "El correo fue enviado exitosamente.",
        },
      },
      header: {
        exportButton: "Exportar",
        title: "Suscripciones",
        giftSubscription: true,
        titleGiftSubscription: "Regalar suscripcion",
      },
      searchPlaceholder: "Buscar...",
      titleAlertModal: "Estas seguro de eliminar?",
      messageAlertModal: "Quieres eliminar este registro?",
      confirmButtonText: "Si, eliminar",
      titleModalConfirm: "Eliminado exitosamente",
      messageModalConfirm: "El registro fue eliminado exitosamente",
    },
    content: {
      modal: {
        title: "Regalar suscripción",
        labels: {
          files: "Archivos",
          name: "Nombre",
          description: "Descripción",
        },
        buttons: {
          createContent: "Crear contenido",
        },
        messages: {
          nameRequired: "Por favor, ingresa el nombre",
          descriptionRequired: "Por favor, ingresa la descripción",
          emailSentTitle: "Funcion no implementada",
          emailSentMessage: "Se agregara posteriormente",
        },
      },
      header: {
        uploadButton: "Subir",
        title: "Contenido",
      },
      card: {
        createContent: "Crear contenido",
      },
    },
    contentDetail: {
      buttonDetails: "Ver",
      buttonDelete: "Eliminar",
    },
    contentDetailPage: {
      buttonCreate: "Crear",
      buttonEdit: "Editar",
      buttonDetails: "Detalle",
      buttonSave: "Guardar",
      alert: {
        title: "Estás seguro de crear?",
        content: "Lo que no hayas guardado se eliminará.",
        confirmButtonText: "Sí, ir a crear",
        titleSecond: "Creado exitosamente",
        contentSecond: "El registro fue creado exitosamente.",
        titleThird: "Editado exitosamente",
        contentThird: "El registro fue editado exitosamente.",
      },
      contentoNoSupport: "Tu navegador no soporta el tag de video.",
      messageError: {
        message: "Por favor, el nombre",
        messageDescription: "Por favor, la descripcion del video",
      },
      inputs: {
        name: "Nombre",
        description: "",
      },
    },
    notificationsPage: {
      title: "Notificaciones",
      messageNotList: "Listado vacio...",
    },
    surveysPage: {
      title: "Encuestas",
      buttonPrincipal: "Agregar encuestas",
      mySurveys: "Mis encuestas",
      publicSurveys: "Encuestas publicas",
      active: "Activo",
      desactive: "Desactiva",
      responses: "Respuestas",
      addSurveys: "Agregar encuestas",
      surveysForm: {
        isActive: "Activa",
        startDate: "Fecha de Inicio",
        endDate: "Fecha de Fin",
        title: "Pregunta",
        responses: "Respuestas",
        addResponse: "Agregar Respuesta",
        submitButton: "Agregar Encuesta",
        cancelButton: "Cancelar",
      },
    }
  },
  en: {
    authlayout: {
      dashboard: "Dashboard",
      earnings: "Earnings",
      suscriptions: "Suscriptions",
      suscriptionsList: "List",
      suscriptionsPlans: "My plans",
      notifications: "Notifications",
      notificationsList: "List",
      surveys: "Surveys",
      content: "Content",
      reports: "Reports",
      configuration: "Configuration",
      goToProfile: "Profile Priv",
      logOut: "Log Out",
    },
    dashboard: {
      title: "Dashboard",
      buttonManage: "Manage",
      welcomeMessage: "Welcome name!",
      totalRevenue: "Total Revenue",
      orders: "Orders",
      activeSessions: "Active Sessions",
      totalSessions: "Total Sessions",
      totalRevenueValue: "$10,540",
      ordersValue: "1,056",
      activeSessionsValue: "48",
      totalSessionsValue: "5,420",
      totalRevenuePercentage: "22.45%",
      ordersPercentage: "15.34%",
      activeSessionsPercentage: "18.25%",
      totalSessionsPercentage: "10.24%",
      revenueArrowDirection: "up",
      ordersArrowDirection: "up",
      activeSessionsArrowDirection: "down",
      totalSessionsArrowDirection: "down",
    },
    earnings: {
      title: "Earnings",
      exportButton: "Export",
      exportSuccessTitle: "Email sent!",
      exportSuccessMessage: "The email was sent successfully.",
      searchPlaceholder: "Search...",
      requestPaymentButton: "Request payment",
      printButton: "Print",
      titleModal: "Detail of earning",
      titleAlertModal: "Are you sure to delete?",
      messageAlertModal: "Do you want to delete this record?",
      confirmButtonText: "Yes, delete",
      titleModalConfirm: "Deleted successfully",
      messageModalConfirm: "The register has deleted successfully",
      columns: {
        name: "Name",
        date: "Date",
        status: "Status",
        content: "Content",
        quantity: "Quantity",
        acctions: "Acctions",
      },
    },
    subscriptions: {
      columns: {
        image: "Image",
        name: "Name",
        date: "Date",
        quantity: "Quantity",
        actions: "Actions",
      },
      modal: {
        title: "Gift subscription",
        labels: {
          email: "Email",
        },
        buttons: {
          giftSubscription: "Gift Sub",
        },
        messages: {
          emailRequired: "Please enter your email",
          emailInvalid: "Please enter a valid email",
          emailSentTitle: "Email sent!",
          emailSentMessage: "The email was sent successfully.",
        },
      },
      header: {
        exportButton: "Export",
        title: "Subscriptions",
        giftSubscription: true,
        titleGiftSubscription: "Gift subscription",
      },
      searchPlaceholder: "Search...",
      titleAlertModal: "Are you sure to delete?",
      messageAlertModal: "Do you want to delete this record?",
      confirmButtonText: "Yes, delete",
      titleModalConfirm: "Deleted successfully",
      messageModalConfirm: "The register has deleted successfully",
    },
    content: {
      modal: {
        title: "Gift subscription",
        labels: {
          files: "Files",
          name: "Name",
          description: "Description",
        },
        buttons: {
          createContent: "Create content",
        },
        messages: {
          nameRequired: "Please enter the name",
          descriptionRequired: "Please enter the description",
          emailSentTitle: "Function no implemented",
          emailSentMessage: "Will be implemented in future",
        },
      },
      header: {
        uploadButton: "Upload",
        title: "Content",
      },
      card: {
        createContent: "Create content",
      },
    },
    contentDetail: {
      buttonDetails: "View",
      buttonDelete: "Delete",
    },
    contentDetailPage: {
      buttonCreate: "Create",
      buttonEdit: "Edit",
      buttonDetails: "Details",
      buttonSave: "Save",
      alert: {
        title: "Are you sure to create?",
        content: "What you haven't saved will be deleted.",
        confirmButtonText: "Yes, go to create",
        titleSecond: "Created successfully",
        contentSecond: "The record was created successfully.",
        titleThird: "Edited successfully",
        contentThird: "The record was edited successfully.",
      },
      contentoNoSupport: "Your browser does not support the video tag.",
      messageError: {
        message: "Please enter the name",
        messageDescription: "Please enter the video description",
      },
      inputs: {
        name: "Name",
        description: "Description",
      },
    },
    notificationsPage: {
      title: "Notifications",
      messageNotList: "List empty...",
    },
    surveysPage: {
      title: "Surveys",
      buttonPrincipal: "Add Survey",
      mySurveys: "My Surveys",
      publicSurveys: "Public surveys",
      active: "Active",
      desactive: "Disabled",
      responses: "Responses",
      addSurveys: "Add Survey",

    }
  },
};

export default APPTEXT;
